### ISSUE TITLE
Porting the codes to full-system simulator (e.g. gem5)

### ISSUE THREAD

**Issue by majid169** [rdadolf/fathom#22]
Hi,

Thanks for releasing the benchmark.

In our research group, we want to do some architectural analysis on deep learning benchmarks. So, we need to run them on a full-system simulator like gem5. Do you think is it possible to port such a benchmark to gem5?

**Comment by rdadolf** [comment]
Hi Majid,

There's a couple wrinkles doing so, but in theory this should be possible. One problem comes from the overall number of cycles required, which is going to make full-system simulation rather arduous. Another is the sheer number of runtime infrastructure required---TF is not small, nor are the other libraries involved. I'm aware of a couple other groups trying something similar with a simpoint methodology, but it's too early to tell whether it's a good avenue to pursue.

We recognized early on that this would be something people were apt to try, so we've been working on modeling infrastructure to make this rather straightforward. (It's an extension of the analysis tool we allude to in the paper.) Sadly, this tool isn't operational yet, so we don't have code to give you. We will release it as open-source software as soon as it's ready.

For the moment, I'm going to close this ticket, since we don't have a clear plan to make Fathom more amenable to gem5 or other simulators. That said, we're not opposed to it, so if you do end up attempting it and discover changes to Fathom that would make it easier, please let us know.
